version: '3.8'

services:
  backend:
    image: josephjimenezs/video-editor-backend:latest
    container_name: video-processor-backend
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5000
    volumes:
      - ./data:/data
    networks:
      - video-processor-network
    restart: unless-stopped

  frontend:
    image: josephjimenezs/video-editor-frontend:latest
    container_name: video-processor-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - video-processor-network
    restart: unless-stopped

networks:
  video-processor-network:
    driver: bridge
