name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check secret length
        run: |
          echo -n "${{ secrets.DOCKER_PASSWORD }}" | wc -c
    
      - name: Manual Docker login test
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Debug secrets
        run: |
          if [ -z "$DOCKER_USERNAME" ]; then echo "USERNAME EMPTY"; else echo "USERNAME OK"; fi
          if [ -z "$DOCKER_PASSWORD" ]; then echo "PASSWORD EMPTY"; else echo "PASSWORD OK"; fi
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/video-processor-backend:latest
      
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/video-processor-frontend:latest
